---
ARPEGE:
  filename_intqv: 'tciwv_ARPNH_20160801-20160910_hourmean.nc'
  filename_cape: 'cape_ARPNH_20160801-20160910_hourmean.nc'
  filename_t2m: 't2m_ARPNH_20160801-20160910_hourmean.nc'
  filename_q2m: '2sh_1hr_-60_60_20160801-20160909.nc'
  filename_ps: 'sp_1hr_-60_60_20160802-20160909.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'tciwv'
  cape: 'CAPE_INS'
  t2m: '\2t'
  q2m: '\2sh'
  ps: 'sp'
FV3:
  filename_intqv: 'fv3_intqv_0.10deg_-60_60_hourmean.nc'
  filename_cape: 'fv3_cape_0.10deg_-60_60_hourmean.nc'
  filename_t2m: 'fv3_t2m_0.10deg_-60_60_hourmean.nc'
  filename_ps: 'fv3_ps_hourmean_0.10deg.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'intqv'
  cape: 'cape'
  t2m: 't2m'
  q2m: ''
  ps: 'ps'
IFS:
  filename_intqv: 'intqv_ifs_0.1deg.nc'
  filename_cape: 'cape_IFS_60S-60N_hourmean.nc'
  filename_t2m: 't2m_IFS_60S-60N_hourmean.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'tcwv'
  cape: 'cape'
  t2m: 't2m'
  q2m: ''
MPAS: 
  filename_intqv: 'MPAS_3.75km_vert_int_qv_0.10deg_-60_60_hourmean.nc'
  filename_cape: 'MPAS_3.75km_cape_0.10deg_-60_60_hourmean.nc'
  filename_t2m: 'MPAS_3.75km_t2m_0.10deg_-60_60_hourmean.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'vert_int_qv'
  cape: 'cape'
  t2m: 't2m'
  q2m: ''
NICAM:
  filename_intqv: 'sa_vap_atm_summer_0.1deg_hourmean.nc'
  filename_t2m: 'ss_t2m_1hr_summer_0.1deg.nc'
  filename_q2m: 'ss_q2m_1hr_summer_0.1deg.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'sa_vap_atm'
  t2m: 'ss_t2m'
  q2m: 'ss_q2m'
SAM:
  filename_intqv: 'SAM_1hr_PW_0.10deg.nc'
  filename_t2m_q2m: 't2m_q2m_mergetime.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'PW'
  t2m: 'T2m'
  q2m: 'Q2m'
SCREAMv1:
  filename_intqv: 'tcwv_scream_summer.nc'
  filename_t2m: 'T_2m_1hr_20160801-20160909_60S-60N.nc'
  filename_q2m: 'qv_2m_1hr_20160801-20160909_60S-60N.nc'
  filename_ps: 'ps_1hr_20160801-20160909_60S-60N.nc'
  filename_lhx: 'surf_evap_1hr_20160801-20160909_60S-60N.nc'
  filename_shx: 'surf_sens_flux_1hr_20160801-20160909_60S-60N.nc'
  filename_wspd10m: 'wind_speed_10m_1hr_20160801-20160909_60S-60N.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'VapWaterPath'
  t2m: 'T_2m'
  q2m: 'qv_2m'
  ps: 'ps'
  lhx: 'surf_evap'
  shx: 'surf_sens_flux'
  wspd10m: 'wind_speed_10m'
UM:
  filename_intqv: 'prw_1hr_HadGEM3-GA71_hourmean.nc'
  filename_cape: 'cape_1hr_HadGEM3-GA71_hourmean.nc'
  filename_t2m_q2m: 't2m_huss_um.nc'
  xcoord_name: 'lon'
  ycoord_name: 'lat'
  intqv: 'atmosphere_water_vapor_content'
  cape: ''
OBS:
  dirname: '/global/cfs/projectdirs/m3522/cmip6/ERA5/e5.oper.an.sfc/'
  file_basename: 'e5.oper.an.sfc.128_'
  intqv_basename: '137_tcwv.ll025sc.'
  cape_basename: '059_cape.ll025sc.'
  xcoord_name: 'longitude'
  ycoord_name: 'latitude'
  intqv: 'TCWV'
  cape: 'CAPE'
  nx: 12
  ny: 12
OBSv7:
  dirname: '/global/cfs/projectdirs/m3522/cmip6/ERA5/e5.oper.an.sfc/'
  file_basename: 'e5.oper.an.sfc.128_'
  intqv_basename: '137_tcwv.ll025sc.'
  cape_basename: '059_cape.ll025sc.'
  xcoord_name: 'longitude'
  ycoord_name: 'latitude'
  intqv: 'TCWV'
  cape: 'CAPE'
  nx: 12
  ny: 12